### ISSUE TITLE
[1.20.2] Vanilla clients can't connect

### ISSUE THREAD

**Issue by tesseract-two** [SFort/MC-OCAIP#6]
Attempting to connect to a server with OCAIP with a vanilla client fails with this error message:
`Internal Exception: io.netty.handler.codec.DecoderException: java.lang.IndexOutOfBoundsException: readerIndex(6) + length(1) exceeds writerIndex(6): PooledUnsafeDirectByteBuf(ridx: 6, widx: 6, cap: 6)`

Client:
Vanilla Minecraft 1.20.2, launched from Prism Launcher

Server:
Minecraft 1.20.2
Fabric Loader 0.14.25
OCAIP 1.3.3

OCAIP config:
````
; Registration password
password=two
; Require OCAIP login
requireOCAIP=false
; Registration sha1pow zero count (complexity, higher value is more time)
sha1pow.zero=
; Registration sha1pow count
sha1pow.count=
````

**Comment by SFort** [comment]
Note that i haven't tested (because i really don't wanna renew MS tokens) but i'm nearly certain that was the bug, thanks for the report

**Comment by tesseract-two** [comment]
It's working perfectly now, thank you!
