### ISSUE TITLE
[1.20.2] Breaks with Fabric API

### ISSUE THREAD

**Issue by tesseract-two** [SFort/MC-OCAIP#7]
When Fabric API and OCAIP are on the server, an OCAIP-enabled client fails to connect with the error message `Unexpected custom data from client`.

```
Server:
Minecraft 1.20.2
Fabric Loader 0.14.25
OCAIP 1.3.3
Fabric API 0.91.1, 0.90.7, and 0.89.0

Client: 
Minecraft 1.20.2
Fabric Loader 0.14.25
OCAIP 1.3.3
```

It also breaks when Fabric API is on **only** the client with this error:
`Internal Exception: io.netty.handler.codec.DecoderException: java.lang.IndexOutOfBoundsException: readerIndex(6) + length(1) exceeds writerIndex(6): PooledUnsafeDirectByteBuf(ridx: 6, widx: 6, cap: 6)`

```
Client: 
Minecraft 1.20.2
Fabric Loader 0.14.25
OCAIP 1.3.3
Fabric API 0.91.1

Server:
Minecraft 1.20.2
Fabric Loader 0.14.25
OCAIP 1.3.3
```

When Fabric API is on both the client and the server, it fails with: `Unexpected custom data from client`.
```
Client: 
Minecraft 1.20.2
Fabric Loader 0.14.25
OCAIP 1.3.3
Fabric API 0.91.1

Server:
Minecraft 1.20.2
Fabric Loader 0.14.25
OCAIP 1.3.3
Fabric API 0.91.1
```

When neither side has Fabric API, everything works perfectly.

OCAIP configuration used throughout:
```
; Registration password
password=two
; Require OCAIP login
requireOCAIP=false
; Registration sha1pow zero count (complexity, higher value is more time)
sha1pow.zero=
; Registration sha1pow count
sha1pow.count=
```

**Comment by SFort** [comment]
having an official big API seams to reliably degrade into forge and seamingly no care is put into injections.

anyhow salt aside, probably fixed i'm outa time to test thoroughly, thanks for the report.

**Comment by tesseract-two** [comment]
Works in my testing, thank you!
