### ISSUE TITLE
[1.20.2] MS players can't connect when Fabric API is installed

### ISSUE THREAD

**Issue by tesseract-two** [SFort/MC-OCAIP#8]
I'm back, sorry. MS players can't join when both Fabric API & OCAIP are installed.

Without FAPI: 
OCAIP players & MS players can connect.

With FAPI:
OCAIP players can connect, MS players get stuck on an "encrypting" screen until they time out with `Failed to connect to the server: Took to long to log in`.

Client logs:
`[14:42:01] [Render thread/INFO]: Connecting to localhost, 25565`

Server logs:
```
[14:42:02] [User Authenticator #1/INFO]: UUID of player **** is **************
[14:42:31] [Server thread/INFO]: Disconnecting **** (/127.0.0.1:45812): Took too long to log in
[14:42:31] [Server thread/INFO]: *redacted_player_name* (/127.0.0.1:45812) lost connection: Took too long to log in
[14:42:31] [Server thread/WARN]: handleDisconnection() called twice
```
Client is vanilla 1.20.2
Server info:
```
Minecraft 1.20.2
Fabric Loader 0.15.1 (tried 0.15.0)
Fabric API 0.91.2  (tried 0.91.1)
OCAIP 0.3.4
```
I'm willing to help with debugging (I know you don't want to refresh your MS token).

**Comment by SFort** [comment]
> I'm willing to help with debugging (I know you don't want to refresh your MS token).

Clever (almost like i made the mod for a reason or something ;p)

**Comment by SFort** [comment]
try this [1.zip](https://github.com/SFort/MC-OCAIP/files/13620695/1.zip).
it's a compleate uniformed yet educated shot in the dark that probably won't work?
but as you said i really don't wanna refresh the token but i guess i'll have to otherwise

**Comment by tesseract-two** [comment]
Unfortunately it didn't work. I got the same freezing on encrypting, then time out.

> Clever (almost like i made the mod for a reason or something ;p)

;D

**Comment by SFort** [comment]
> but i guess i'll have to otherwise

turn out i lied, here another random guess.

[2.zip](https://github.com/SFort/MC-OCAIP/files/13624627/2.zip)

also please clarify exactly what is on client and what is on server.
is the client vanilla or do both bave ocaip+fapi?

**Comment by tesseract-two** [comment]
Same error :(

Client is pure vanilla, server is fapi+ocaip. It works if you have OCAIP + are offline, otherwise it doesn't seem to care what client mods you have.

**Comment by SFort** [comment]
[3.zip](https://github.com/SFort/MC-OCAIP/files/13625641/3.zip)

**Comment by tesseract-two** [comment]
It works! Thank you!

> REMOVING FAPIs ServerLoginNetworkHandlerMixin as it is soo poorly made it shouldn't exist, this may break some login networking, feel free to discuss this at https://github.com/FabricMC/fabric

:P

**Comment by SFort** [comment]
I'll try and add a config for removing the inject and release it tommorow

**Comment by SFort** [comment]
frankly i haven't tried to understand what the api is even trying to do.
because there's no existance where this injection makes sense.
since even if it was the perfect inject, which it is deffinatly fucking not.
You would never want to put this kind of thing in an install without making sure the user actually has a mod installed that needs it. While fapi is included in almost all installs making this just so increadibly bad that i'mma spend the remained of the day with icecream pretending fabric api can't ruin anything else (which clearly isn't true, their trying their best).

**Comment by tesseract-two** [comment]
Seriously thank you for going to all this trouble to fix someone else's use case.
